name: 'CodeQL: Query'
description: 'Run a CodeQL query against a repository'
author: 'GitHub'
inputs:
  query:
    description: 'Text of CodeQL query to run'
    required: true

  language:
    description: 'Language of CodeQL query'
    required: true

  repositories:
    description: 'Repositories to run the query against'
    required: true

  token:
    description: 'token to use to fetch the databases to query'
    required: true

  codeql:
    description: 'path to CodeQL binary to use'
    required: true
runs:
  using: 'node12'
  main: '../lib/query.js'
