name: "Integration tests label check"

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

jobs:
  integration-tests-have-been-run:
    runs-on: ubuntu-latest
    steps:
      - name: Check label is present on PR
        run: |
          gh api "/repos/$GITHUB_REPOSITORY/issues/${{ github.event.pull_request.number }}/labels" | jq -r '.[].name' | grep "integration tests succeeded"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
