### Temporary test file! See also https://github.com/dsp-testing/qc-run2/pull/65#discussion_r719307551
name: CodeQL query

on:
  workflow_dispatch:
    inputs:
      query:
        description: "Text of CodeQL query to run."
        required: true

      language:
        description: "Language of CodeQL query"
        required: true

      # Handle this input very carefully as it contains sensitive data such as the authentication tokens!
      repositories:
        description: "Repositories to run the query against. A JSON encoded array of the form {id: number, nwo: string, token: string}[]"
        required: true

      repoIdChunks:
        description: "Array of arrays of repository ids. Each of the inner arrays will be processed in a separate job"
        required: true

jobs:
  top:
    uses: dsp-testing/qc-run2/.github/workflows/codeql-query.yml@handle-failure
    secrets:
      ACTIONS_STEP_DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}
